TOP=../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#========================================

#----------------------------------------
#  ADD RULES AFTER THIS LINE
#========================================
include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXPLICIT DEPENDENCIES AFTER THIS LINE